name: Update README with JSON Data

on:
  schedule:
    - cron: '0 20 * * *'  # Runs at 8 PM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all bases

      - name: Fetch and update README
        run: |
          curl -s -o doing.json https://raw.githubusercontent.com/RyuZinOh/static-assets/main/doing.json

          jq -r '.repositories[] | "- [\(.name)](\(.url)): \(.motive)"' doing.json > new_doing_content.txt

          sed -i '/<!-- doing start -->/,/<!-- doing end -->/{//!d}' README.md
          sed -i '/<!-- doing start -->/r new_doing_content.txt' README.md

          rm doing.json new_doing_content.txt

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git pull --rebase
          
          git add README.md
          git commit -m "docs: update README with project list" || echo "No changes to commit"
          
          git push
